src/accounts/urls.py
#!/usr/bin/env python3

from django.urls import path
from .views import SignupView, LoginView, LogoutView, AuthStatusView, ProfileView, ProfileEditView, ProfileDeleteView, ResetPasswordView, UserView, verify_email, SendSignInEmail, EmailSentView, ForgottenPasswordView, PasswordResetRequestView, SetNotificationsView, ApplicationSentView

urlpatterns = [
    path('opret/', SignupView.as_view(), name='signup'),
    path('log-ind/', LoginView.as_view(), name='login'),
    path('log-ud/', LogoutView.as_view(), name='logout'),
    path('auth-status/', AuthStatusView.as_view(), name='auth_status'),
    path('ret/', ProfileEditView.as_view(), name='profile_edit'),
    path('slet/', ProfileDeleteView.as_view(), name='profile_delete'),
    path('', ProfileView.as_view(), name='profile'),
    path('skift-kode/', ResetPasswordView.as_view(), name='reset_password'),
    path('<int:pk>/', UserView.as_view(), name='user'),
    path('sign-in', SendSignInEmail.as_view(), name='sign_in'),
    path('verify-email/<uidb64>/<token>/', verify_email, name='verify_email'),
    path('tilmelding-sendt/<str:email>/', ApplicationSentView.as_view(), name='application_sent'),
    path('email-sendt/<int:pk>/', EmailSentView.as_view(), name='email_sent'),
    path('ny-kode/<uidb64>/<token>/', ForgottenPasswordView.as_view(), name='forgotten_password'),
    path('ny-kode/', PasswordResetRequestView.as_view(), name='reset_request'),
    path('notifikationer/', SetNotificationsView.as_view(), name='notifications'),
]

src/hzd/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views 

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('aar/', views.YearView.as_view(), name='years'),
    path('aar/opret/', views.YearCreate.as_view(), name='year_create'),
    path('aar/tilpas/<int:pk>/', views.YearEdit.as_view(), name='year'),
    path('aar/slet/<int:pk>/', views.YearDeleteView.as_view(), name='year_delete'),
    path('booking/<int:year>/', views.BookingView.as_view(), name='bookings'),
    path('booking/opret/', views.BookingCreate.as_view(), name='booking_create'),
    path('booking/tilpas/<int:pk>/', views.BookingEdit.as_view(), name='booking'),
    path('booking/slet/<int:pk>/', views.BookingDeleteView.as_view(), name='booking_delete'),
    path('frivillige/<int:year>/', views.VolunteerView.as_view(), name='volunteers'),
    path('frivillige/opret/', views.VolunteerCreate.as_view(), name='volunteer_create'),
    path('frivillige/tilpas/<int:pk>/', views.VolunteerEdit.as_view(), name='volunteer'),
    path('frivillige/slet/<int:pk>/', views.VolunteerDeleteView.as_view(), name='volunteer_delete'),
    path('sider/', views.PageView.as_view(), name='pages'),
    path('sider/tilpas/<int:pk>/', views.PageEdit.as_view(), name='page'),
    path('sider/slet/<int:pk>/', views.PageDeleteView.as_view(), name='page_delete'),
    path('donationer/', views.DonationView.as_view(), name='donations'),
    path('donationer/opret/', views.DonationCreate.as_view(), name='donation_create'),
    path('donationer/tilpas/<int:pk>/', views.DonationEdit.as_view(), name='donation'),
    path('donationer/slet/<int:pk>/', views.DonationDeleteView.as_view(), name='donation_delete'),
    path('events/', views.EventView.as_view(), name='events'),
    path('events/create/', views.EventCreate.as_view(), name='event_create'),
    path('events/tilpas/<int:pk>/', views.EventEdit.as_view(), name='event'),
    path('events/slet/<int:pk>/', views.EventDeleteView.as_view(), name='event_delete'),
    path('kunstnere/', views.ArtistView.as_view(), name='artists'),
    path('kunstnere/opret/', views.ArtistCreate.as_view(), name='artist_create'),
    path('kunstnere/slet/<int:pk>/', views.ArtistDeleteView.as_view(), name='artist_delete'),
    path('kunstnere/tilpas/<int:pk>/', views.ArtistEdit.as_view(), name='artist'),
    path('kunstnere/profil/<int:pk>', views.ArtistProfileView.as_view(), name='artist_profile'),
    path('program/<int:year>/', views.ProgramView.as_view(), name='programs'),
    path('program/opret/', views.ProgramCreate.as_view(), name='program_create'),
    path('program/tilpas/<int:pk>/', views.ProgramEdit.as_view(), name='program'),
    path('program/slet/<int:pk>/', views.ProgramDeleteView.as_view(), name='program_delete'),
    path('omraader/<int:year>/', views.VolunteerAreaView.as_view(), name='areas'),
    path('omraader/opret/', views.VolunteerAreaCreate.as_view(), name='area_create'), 
    path('omraader/opret/<int:pk>', views.VolunteerAreaCreate.as_view(), name='area_create_with_id'), 
    path('omraader/tilpas/<int:pk>/', views.VolunteerAreaEdit.as_view(), name='area'), 
    path('omraader/slet/<int:pk>/', views.VolunteerAreaDeleteView.as_view(), name='area_delete'), 
    path('mails/', views.MailView.as_view(), name='mails'), 
    path('mails/opret/', views.MailCreateView.as_view(), name='mail_create'), 
    path('mails/tilpas/<int:pk>/', views.MailEditView.as_view(), name='mail'), 
    path('mails/slet/<int:pk>/', views.MailDeleteView.as_view(), name='mail_delete'), 
    path('send_mail/', views.SendMailView.as_view(), name='send_mail'), 
    path('vagter/<int:area>', views.VolunteerShiftView.as_view(), name='shifts'), 
    path('vagter/opret/', views.VolunteerShiftCreateView.as_view(), name='shift_create'), 
    path('vagter/tilpas/<int:pk>/', views.VolunteerShiftEditView.as_view(), name='shift'), 
    path('vagter/slet/<int:pk>/', views.VolunteerShiftDeleteView.as_view(), name='shift_delete'), 
    path('save-shift-assignments/', views.save_shift_assignments, name='save_shift_assignments'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/nakkefestival/urls.py
from django.contrib import admin
from django.urls import include, path
from ckeditor_uploader import views as ckeditor_views

urlpatterns = [
    path("", include(("year.urls", "year"), namespace="year")),
    path("hzd/", include(("hzd.urls", "hzd"), namespace="hzd")),
    path("admin/", admin.site.urls),
    path("profil/", include(("accounts.urls", "accounts"), namespace="accounts")),  # new
    path("profil/", include("django.contrib.auth.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('openid/', include('oidc_provider.urls', namespace='oidc_provider')),
]

src/year/urls.py
from django.urls import path

from django.conf.urls import handler403
from . import views

app_name = "year"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('information/praktisk_information', views.Praktisk_informationView.as_view(), name='praktisk_information'),
    path('information/bliv_frivillig', views.Bliv_frivilligView.as_view(), name='bliv_frivillig'),
    path('information/bliv_kunstner', views.Bliv_kunstnerView.as_view(), name='bliv_kunstner'),
    path('information/fallesbus_til_nakke', views.Fallesbus_til_nakkeView.as_view(), name='fællesbus_til_nakke'),
    path('om/om_nakkefestival', views.Om_nakkefestivalView.as_view(), name='om_nakkefestival'),
    path('om/historien', views.HistorienView.as_view(), name='historien'),
    path('om/find_vej', views.Find_vejView.as_view(), name='find_vej'),
    path('om/billeder', views.BillederView.as_view(), name='billeder'),
    path('om/donationer', views.DonationerView.as_view(), name='donationer'),
    path('om/vedtagter', views.VedtagterView.as_view(), name='vedtagter'),
    path('om/presse', views.PresseView.as_view(), name='presse'),
    path('om/kontakt', views.KontaktView.as_view(), name='kontakt'),
    path('musik/kunstnere/<int:year>/', views.KunstnereView.as_view(), name='kunstnere'),
    # path('musik/kunstnere/<int=year>', views., name=''),
    # path('musik/kunstnere/<slug=band>', view., name''),
    path('musik/program/<int:year>/', views.ProgramView.as_view(), name='program'),
    # path('<int:year>?/musik/program', views.ProgramView.as_view(), name='program'),
    path('musik/events/<int:year>/', views.EventsView.as_view(), name='events'),
    path('kunstner_tilmelding/', views.SendApplicationView.as_view(), name='send_application'),
    path('om/privatlivspolitik/', views.PrivacyView.as_view(), name='privacy'),
] 


handler403 = views.CustomPermissionDeniedView.as_view()

src/hzd/models.py
from django.db import models

# Create your models here.

src/year/forms.py
from django import forms
from django.utils import timezone
from datetime import timedelta, date
from year.models import Year, Page, Donation, Event, Artist, Program, ApplicationStatus, ArtistApplication, Venue, Concert, Genre, ArtistManagement, VolunteerApplication, VolunteerArea, VolunteerShift
from accounts.models import User, Mail
from django.contrib.postgres.forms import SimpleArrayField
from django.utils.timezone import localtime
from django.core.exceptions import ValidationError
from django.db.models import F
from django.shortcuts import redirect, get_object_or_404 
from ckeditor.widgets import CKEditorWidget
 
class SendApplicationForm(forms.Form):
    required_css_class = 'required'
    
    contact = forms.CharField(
            required=True,
            label="Kontaktpersons navn"
            )
    email = forms.EmailField(
            required=True,
            label="Email"
            )
    phone = forms.CharField(
            required=True,
            label="Telefon"
            )
    alt_contact = forms.CharField(
            required=False,
            label="Alternativ kontaktmulighed"
            )
    name = forms.CharField(
            required=True,
            label="Kunstnernavn"
            )
    description = forms.CharField(
            widget=CKEditorWidget(), 
            required=True,
            label="Beskrivelse", 
            )
    image = forms.ImageField(
            required=False,
            label="Billede",
            )
    link = forms.URLField(
            required=False,
            label="Link"
            )
    file = forms.FileField(
            required=False,
            label="Fil"
            )
    comment = forms.CharField(
            required=False,
            label="Kommentarer",
            widget=forms.Textarea,
            )
    
    def __init__(self, *args, **kwargs):
        super(SendApplicationForm, self).__init__(*args, **kwargs)

        # Apply the 'form-control' class to all visible fields
        for field_name, field in self.fields.items():
            if field.widget.__class__.__name__ != 'HiddenInput':
                field.widget.attrs['class'] = 'form-control'
    
    def clean(self):
        if not self.cleaned_data['link'] and not self.cleaned_data['file']:
            raise ValidationError("Du skal tilføje musik som link eller fil.")

src/year/templates/hzd/volunteers/index.html
<!-- index.html -->
{% extends "year/page.html" %}
{% block page_content %}

<div class="row mb-3">
  <div class="dropdown bello text-center">
    <button class="btn opacity-25 dropdown-toggle" style="font-size:2rem;" type="button" id="dropdownSelectButton" data-bs-toggle="dropdown" aria-expanded="false">
      <b style="font-size:3rem">{{ year }}</b> 
    </button>
    <ul class="dropdown-menu scroller" aria-labelledby="dropdownSelectButton" style="max-height:15rem;overflow-y:scroll;">
      {% for year_obj in every_year %}
        <li class="dropdowm-item ">
          <a class="dropdown-item d-block" href="{% url 'hzd:volunteers' year=year_obj.year %}">{{ year_obj.year }}</a> 
        </li>
      {% endfor %}
    </ul>
  </div>
</div>

<div class="d-flex justify-content-end mb-3">
  <a class="btn btn-primary" href="{% url 'hzd:volunteer_create' %}?next={{ request.path }}">
    <i class="fa fa-plus-circle" aria-hidden="true"> Opret Frivillig</i>
  </a>
</div>

{% if volunteer_applications %}
  <div class="table-container">
      <table class="table table-striped table-bordered table-hover">
          <thead>
              <th class="d-none d-sm-table-cell">
                <a class="btn btn-primary" href="?sort=year&order={% if current_sort == 'year' and next_order == 'desc' %}desc{% else %}asc{% endif %}">
                  <b>År</b>
                </a>
              </th>
              <th class="d-none d-sm-table-cell">
                <a class="btn btn-primary" href="?sort=time&order={% if current_sort == 'time' and next_order == 'asc' %}asc{% else %}desc{% endif %}">
                  Ansøgningstid
                </a>
              </th>
              <th class="overflow-hidden text-truncate">
                <a class="btn btn-primary" href="?sort=area&order={% if current_sort == 'area' and next_order == 'asc' %}asc{% else %}desc{% endif %}">
                  Område
                </a>
              </th>
              <th class="overflow-hidden text-truncate">
                <a class="btn btn-primary" href="?sort=user&order={% if current_sort == 'user' and next_order == 'asc' %}asc{% else %}desc{% endif %}">
                  Ansøger
                </a>
              </th>
              <th class="overflow-hidden text-truncate">
                <a class="btn btn-primary" href="?sort=status&order={% if current_sort == 'status' and next_order == 'asc' %}asc{% else %}desc{% endif %}">
                  Status
                </a>
              </th>
              <th></th>
          </thead>
          <tbody>
              {% for application in volunteer_applications %}
                {% if application %}
                  <tr class="clickable-row" data-href="{% url 'hzd:volunteer' pk=application.pk %}?next={{ request.path }}">
                    <td class="d-none d-sm-table-cell"><b>{{ application.year }}</b></td>
                    <td class="d-none d-sm-table-cell">{{ application.time }}</td>
                    <td class="sm-truncate">{{ application.area }}</td>
                    <td class="sm-truncate">{{ application.user }}</td>
                    <td class="sm-truncate">{{ application.status }}</td>
                    <td>
                      <a href="{% url 'hzd:volunteer' pk=application.pk %}?next={{ request.path }}"><i class="bi bi-pencil-square"></i></a>
                      <br>
                      <a href="{% url 'hzd:shifts' area=application.area.pk %}?next={{ request.path }}">
                        <i class="fa fa-users" aria-hidden="true"></i>
                      </a>
                    </td>
                  </tr>
                {% endif %}
              {% endfor %}
          </tbody>
      </table>
  </div>
{% else %}
  <p>There are no pages to be displayed</p>
{% endif %}

{% endblock %}

src/year/templates/hzd/volunteers/volunteer.html
{% extends "year/page.html" %}
{% block page_content %}
<div class="container" style="background:rgb(200,235,253,0.5)">
  <a href="{% url 'accounts:user' pk=user.pk %}">
    <h2>{{ user.username }}</h2>
  </a>
  <dl>
    <dt>
      Navn
    </dt>
    <dd>
      <p>{{ user.first_name }} {{ user.last_name }}</p>
    </dd>
    <dt>
      Email
    </dt>
    <dd>
      <p>{{ user.email }}</p>
    </dd>
    <dt>
      Telefon
    </dt>
    <dd>
      <p>{{ user.phone }}</p>
    </dd>
    <dt>
      Adresse
    </dt>
    <dd>
      <p>{{ user.address.street }} {{ user.address.number }}, {{ user.address.post }}</p>
    </dd>
    <dt>
      Fødselsdato
    </dt>
    <dd>
      <p>{{ user.birthdate }}</p>
    </dd>
  </dl>
</div>
<div style="background-image: url('{{ bg.image_url }}');">
    <!-- Include the reusable form template -->
    {% include 'form_snippet.html' with form=form method='post' action='' button_label='Opdater' %}
</div>

<!-- Delete Modal -->
{% if button_label_delete %}
  <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" style="min-width:50vw;">
      <div class="modal-content" style="background-size:cover; background-image:url('{{ STATIC_DEV|add:"img/bg/home.jpg" }}');">
        <div class="modal-header">
          <h1 class="modal-title bello" id="exampleModalLabel">Slet</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Er du sikker?</p>
        </div>
        <div class="modal-footer">
          <form method="post" action="{% url 'hzd:volunteer_delete' volunteer_edit.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Slet det</button>
          </form>
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal" aria-label="Close">
            <p>Fortryd</p>
          </button>
        </div>
      </div>
    </div>
  </div>
{% endif %}

{% endblock page_content %}