src/hzd/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views 

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('aar/', views.YearView.as_view(), name='years'),
    path('aar/opret/', views.YearCreate.as_view(), name='year_create'),
    path('aar/tilpas/<int:pk>/', views.YearEdit.as_view(), name='year'),
    path('aar/slet/<int:pk>/', views.YearDeleteView.as_view(), name='year_delete'),
    path('booking/<int:year>/', views.BookingView.as_view(), name='bookings'),
    path('booking/opret/', views.BookingCreate.as_view(), name='booking_create'),
    path('booking/tilpas/<int:pk>/', views.BookingEdit.as_view(), name='booking'),
    path('booking/slet/<int:pk>/', views.BookingDeleteView.as_view(), name='booking_delete'),
    path('frivillige/<int:year>/', views.VolunteerView.as_view(), name='volunteers'),
    path('frivillige/opret/', views.VolunteerCreate.as_view(), name='volunteer_create'),
    path('frivillige/tilpas/<int:pk>/', views.VolunteerEdit.as_view(), name='volunteer'),
    path('frivillige/slet/<int:pk>/', views.VolunteerDeleteView.as_view(), name='volunteer_delete'),
    path('sider/', views.PageView.as_view(), name='pages'),
    path('sider/tilpas/<int:pk>/', views.PageEdit.as_view(), name='page'),
    path('sider/slet/<int:pk>/', views.PageDeleteView.as_view(), name='page_delete'),
    path('donationer/', views.DonationView.as_view(), name='donations'),
    path('donationer/opret/', views.DonationCreate.as_view(), name='donation_create'),
    path('donationer/tilpas/<int:pk>/', views.DonationEdit.as_view(), name='donation'),
    path('donationer/slet/<int:pk>/', views.DonationDeleteView.as_view(), name='donation_delete'),
    path('events/', views.EventView.as_view(), name='events'),
    path('events/create/', views.EventCreate.as_view(), name='event_create'),
    path('events/tilpas/<int:pk>/', views.EventEdit.as_view(), name='event'),
    path('events/slet/<int:pk>/', views.EventDeleteView.as_view(), name='event_delete'),
    path('kunstnere/', views.ArtistView.as_view(), name='artists'),
    path('kunstnere/opret/', views.ArtistCreate.as_view(), name='artist_create'),
    path('kunstnere/slet/<int:pk>/', views.ArtistDeleteView.as_view(), name='artist_delete'),
    path('kunstnere/tilpas/<int:pk>/', views.ArtistEdit.as_view(), name='artist'),
    path('kunstnere/profil/<int:pk>', views.ArtistProfileView.as_view(), name='artist_profile'),
    path('program/<int:year>/', views.ProgramView.as_view(), name='programs'),
    path('program/opret/', views.ProgramCreate.as_view(), name='program_create'),
    path('program/tilpas/<int:pk>/', views.ProgramEdit.as_view(), name='program'),
    path('program/slet/<int:pk>/', views.ProgramDeleteView.as_view(), name='program_delete'),
    path('omraader/<int:year>/', views.VolunteerAreaView.as_view(), name='areas'),
    path('omraader/opret/', views.VolunteerAreaCreate.as_view(), name='area_create'), 
    path('omraader/opret/<int:pk>', views.VolunteerAreaCreate.as_view(), name='area_create_with_id'), 
    path('omraader/tilpas/<int:pk>/', views.VolunteerAreaEdit.as_view(), name='area'), 
    path('omraader/slet/<int:pk>/', views.VolunteerAreaDeleteView.as_view(), name='area_delete'), 
    path('mails/', views.MailView.as_view(), name='mails'), 
    path('mails/opret/', views.MailCreateView.as_view(), name='mail_create'), 
    path('mails/tilpas/<int:pk>/', views.MailEditView.as_view(), name='mail'), 
    path('mails/slet/<int:pk>/', views.MailDeleteView.as_view(), name='mail_delete'), 
    path('send_mail/', views.SendMailView.as_view(), name='send_mail'), 
    path('vagter/<int:area>', views.VolunteerShiftView.as_view(), name='shifts'), 
    path('vagter/opret/', views.VolunteerShiftCreateView.as_view(), name='shift_create'), 
    path('vagter/tilpas/<int:pk>/', views.VolunteerShiftEditView.as_view(), name='shift'), 
    path('vagter/slet/<int:pk>/', views.VolunteerShiftDeleteView.as_view(), name='shift_delete'), 
    path('save-shift-assignments/', views.save_shift_assignments, name='save_shift_assignments'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/nakkefestival/urls.py
from django.contrib import admin
from django.urls import include, path
from ckeditor_uploader import views as ckeditor_views

urlpatterns = [
    path("", include(("year.urls", "year"), namespace="year")),
    path("hzd/", include(("hzd.urls", "hzd"), namespace="hzd")),
    path("admin/", admin.site.urls),
    path("profil/", include(("accounts.urls", "accounts"), namespace="accounts")),  # new
    path("profil/", include("django.contrib.auth.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('openid/', include('oidc_provider.urls', namespace='oidc_provider')),
]

src/year/urls.py
from django.urls import path

from django.conf.urls import handler403
from . import views

app_name = "year"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('information/praktisk_information', views.Praktisk_informationView.as_view(), name='praktisk_information'),
    path('information/bliv_frivillig', views.Bliv_frivilligView.as_view(), name='bliv_frivillig'),
    path('information/bliv_kunstner', views.Bliv_kunstnerView.as_view(), name='bliv_kunstner'),
    path('information/fallesbus_til_nakke', views.Fallesbus_til_nakkeView.as_view(), name='fællesbus_til_nakke'),
    path('om/om_nakkefestival', views.Om_nakkefestivalView.as_view(), name='om_nakkefestival'),
    path('om/historien', views.HistorienView.as_view(), name='historien'),
    path('om/find_vej', views.Find_vejView.as_view(), name='find_vej'),
    path('om/billeder', views.BillederView.as_view(), name='billeder'),
    path('om/donationer', views.DonationerView.as_view(), name='donationer'),
    path('om/vedtagter', views.VedtagterView.as_view(), name='vedtagter'),
    path('om/presse', views.PresseView.as_view(), name='presse'),
    path('om/kontakt', views.KontaktView.as_view(), name='kontakt'),
    path('musik/kunstnere/<int:year>/', views.KunstnereView.as_view(), name='kunstnere'),
    # path('musik/kunstnere/<int=year>', views., name=''),
    # path('musik/kunstnere/<slug=band>', view., name''),
    path('musik/program/<int:year>/', views.ProgramView.as_view(), name='program'),
    # path('<int:year>?/musik/program', views.ProgramView.as_view(), name='program'),
    path('musik/events/<int:year>/', views.EventsView.as_view(), name='events'),
    path('kunstner_tilmelding/', views.SendApplicationView.as_view(), name='send_application'),
    path('om/privatlivspolitik/', views.PrivacyView.as_view(), name='privacy'),
] 


handler403 = views.CustomPermissionDeniedView.as_view()

src/hzd/models.py
from django.db import models

# Create your models here.

src/year/models.py
from django.db import models
from accounts.models import User
from django.utils import timezone
from django.contrib.postgres.fields import ArrayField
from ckeditor.fields import RichTextField
from datetime import datetime, time, timedelta
from django.db.models.signals import m2m_changed
from django.dispatch import receiver

class Year(models.Model):
    year = models.IntegerField()
    published = models.BooleanField(default=False)
    start_time = models.DateTimeField(blank=True)
    end_time = models.DateTimeField(blank=True)
    banner_image = models.ImageField(upload_to='images/year/', blank=True)
    
    @classmethod
    def current_year(cls):
        # Set year object to the next year, if only 120 days from next year
        offset_date=timezone.now()+timedelta(days=120)
        offset_year=offset_date.year

        # return year object with offset year
        return cls.objects.get_or_create(year=offset_year)[0]

    def __str__(self):
        return str(self.year)

    class Meta:
        permissions = [
            ("view_hzd", "Can view Hzd"),
            ("access_wiki", "Can access Wiki"),
            ("access_cloud", "Can access Cloud drive"),
            ("access_chat", "Can access Chat"),
            ("access_mail", "Can access Mail"),
        ]

class Page(models.Model):
    year = models.ForeignKey(Year, on_delete=models.CASCADE)
    
    title = models.CharField(max_length=50)
    bg_image = models.ImageField(upload_to='images/pages/', blank=True)
    short_description = models.CharField(max_length=500, blank=True)
    long_description = RichTextField(blank=True)
    organiser_page = models.BooleanField(default=False)
    
    def __str__(self):
        """
        How the record is represented in the django admin interface
        """
        return self.title

class Donation(models.Model):
    year = models.ForeignKey(Year, on_delete=models.CASCADE, related_name='donations')
    
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    receiver = models.CharField(max_length=50)
    published = models.BooleanField(default=False)
    phone = models.CharField(max_length=50, blank=True)
    mail = models.EmailField(blank=True)
    link = models.URLField(blank=True)

    def __str__(self):
        return f'{self.year} - {self.amount} kr.'
    
class Event(models.Model):
    name = models.CharField(max_length=50)
    # img = models.CharField(max_length=250, blank=True)
    short_description = models.CharField(max_length=250, blank=True)
    long_description = RichTextField(max_length=2500, blank=True)
    img = models.ImageField(upload_to='images/events/', blank=True)
    # state = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Artist(models.Model):
    name = models.CharField(max_length=100)
    short_description = models.CharField(max_length=500, blank=True)
    long_description = RichTextField(blank=True, max_length=2500)
    img = models.ImageField(upload_to='images/artists/', blank=True)
    # mp3 = models.CharField(max_length=50, blank=True)
    link_youtube = models.URLField(blank=True)
    link_spotify = models.URLField(blank=True)
    link_soundcloud = models.URLField(blank=True)
    link_bandcamp = models.URLField(blank=True)
    link_other = models.URLField(blank=True)
    user = models.ManyToManyField(User, related_name='artists')
    # state = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        permissions = (
            ('view_allartists', "Can view all artists"),
        )

# Signal handler for ManyToMany field changes on `user`
@receiver(m2m_changed, sender=Artist.user.through)
def delete_artist_if_no_users(sender, instance, action, **kwargs):
    if action == "post_remove":  # Trigger after users are removed
        if instance.user.count() == 0:  # Check if no users remain
            instance.delete()  # Delete the Artist instance

class Stage(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Program(models.Model):
    year = models.ForeignKey(Year, on_delete=models.CASCADE, related_name='programs')
    stage = models.ForeignKey(Stage, on_delete=models.CASCADE, related_name='programs')
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, related_name='programs', blank=True, null=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='programs', blank=True, null=True)

    start_time = models.DateTimeField()
    end_time = models.DateTimeField(null=True,blank=True)
    published = models.BooleanField(default=False)
    
    def __str__(self):
        if self.artist_id: 
            return f'{self.year} - {self.artist_id}'
        else: 
            return f'{self.year} - {self.event_id}'

class ApplicationStatus(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class ArtistApplication(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, related_name='artist_applications')
    year = models.ForeignKey(Year, on_delete=models.CASCADE, related_name='artist_applications')
    time = models.DateTimeField(auto_now_add=True)
    techrider = models.FileField(upload_to='techriders/', blank=True)
    user_comment = models.TextField(blank=True)

    status = models.ForeignKey(ApplicationStatus, on_delete=models.CASCADE, related_name='artist_applications')
    org_comment = RichTextField(blank=True)
    class Meta:
        permissions = (
            ('test_artistapplications', "Can test artist applications"),
            ('view_artistapplicationstatus','Can view artist application status'),
            ('change_artistapplicationstatus','Can change artist application status'),
            ('view_orgcomment', 'Can view artist application organiser comment'),
            ('change_orgcomment', 'Can change artist application organiser comment'),
        )

class Venue(models.Model):
    name = models.CharField(max_length=50)
    adress = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=16, blank=True)
    link = models.CharField(max_length=250, blank=True)

    def __str__(self):
        return self.name

class Concert(models.Model):
    time = models.DateTimeField()
    comment = RichTextField(max_length=250, blank=True)

    def __str__(self):
        return self.time

class Genre(models.Model):
    tag = models.CharField(max_length=50)

    def __str__(self):
        return self.tag

class ArtistManagement(models.Model):
    comment = models.TextField(max_length=250, blank=True)
    votes = models.IntegerField()
    stars = models.IntegerField()
    commentCount = models.IntegerField()

class VolunteerApplication(models.Model):
    year = models.ForeignKey(Year, on_delete=models.CASCADE, related_name='volunteer_application')
    time = models.DateTimeField(auto_now_add=True)
    area = models.ForeignKey("VolunteerArea", on_delete=models.CASCADE, related_name='volunteer_application')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='volunteer_application')
    user_comment = models.TextField(blank=True)
    manager = models.BooleanField(default=False) 
    status = models.ForeignKey(ApplicationStatus, on_delete=models.CASCADE, related_name='volunteer_application')
    org_comment = RichTextField(blank=True)

    def __str__(self):
        return f'{self.area} - {self.time}'
    
    class Meta:
        permissions = [
            ("view_volunteerapplicationstatus", "Can view volunteer application status"),
            ("change_volunteerapplicationstatus", "Can change volunteer application status"),
            ("view_orgcomment", "Can view organiser comment of volunteer application"),
            ("change_orgcomment", "Can change organiser comment of volunteer application"),
            ("change_volunteerapplicationarea", "Can change volunteer area for a volunteer application"),
        ]

class VolunteerArea(models.Model):
    year = models.ForeignKey(Year, on_delete=models.CASCADE, related_name='volunteer_area')
    name = models.CharField(max_length=50)
    published = models.BooleanField()
    mail = models.CharField(max_length=50, blank=True)
    volunteerCount = models.IntegerField(default=0)
    volunteerMax = models.IntegerField()
    managerCount = models.IntegerField(default=0)
    managerMax = models.IntegerField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    bg = models.ImageField(upload_to='images/areas/', blank=True)
    short_description = models.CharField(max_length=250, blank=True)
    long_description = RichTextField(max_length=10000, blank=True)

    def __str__(self):
        return self.name
    
    class Meta:
        permissions = [
            ("view_allareas", "Can view all volunteer areas"),
        ]
    
class TicketType(models.Model):
    year = models.ForeignKey(Year, on_delete=models.CASCADE, related_name='tickettype')
    name = models.CharField(max_length=50)
    price = models.CharField(max_length=50)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    description = models.CharField(max_length=500)
    stock = models.IntegerField()
    onlineSale = models.IntegerField()
    doorSale = models.IntegerField()
    published = models.BooleanField()

    def __str__(self):
        return f'{self.year} - {self.name}'
    
class Ticket(models.Model):
    ticketType = models.ForeignKey("TicketType", on_delete=models.CASCADE, related_name='ticket')
    purchase_date = models.DateField(max_length=50)

    def __str__(self):
        return f'{self.ticketType} - {self.purchase_date}'

class VolunteerShift(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='volunteershift', null=True, blank=True)
    area = models.ForeignKey(VolunteerArea, on_delete=models.CASCADE, related_name='volunteershift')

src/year/templates/hzd/index.html
{% extends "year/page.html" %}
{% block page_content %}
{{ bokeh_script|safe }}
{{ bokeh_script2|safe }}
<div class="row">
  <div class="col-sm">
    {{ bokeh_div|safe }}
  </div>
  <div class="col-sm">
    {{ bokeh_div2|safe }}
  </div>
</div>
<div class="row">
  {% if perms.year.view_page %}
    <div class="col-3 mt-1 pt-1">
      <div class="border border-white border-2 rounded-3 fill-color-bg">
        <a href="{% url 'hzd:pages' %}" class="fill-div">
          <p class="text-center bello h3 mt-2">
            Sider
          </p>
        </a>
      </div>
    </div>
  {% endif %}
  {% if perms.year.view_artistapplication %}
    <div class="col-3 mt-1 pt-1">
      <div class="border border-white border-2 rounded-3 fill-color-bg">
        <a href="{% url 'hzd:bookings' year=current_year %}" class="fill-div">
          <p class="text-center bello h3 mt-2">
            Bookings
          </p>
        </a>
      </div>
    </div>
  {% endif %}
  {% if perms.year.view_volunteerapplication %}
    <div class="col-3 mt-1 pt-1">
      <div class="border border-white border-2 rounded-3 fill-color-bg">
        <a href="{% url 'hzd:volunteers' year=current_year %}" class="fill-div">
          <p class="text-center bello h3 mt-2">
            Frivillige
          </p>
        </a>
      </div>
    </div>
  {% endif %}
  {% if perms.year.access_wiki %}
    <div class="col-3 mt-1 pt-1">
      <div class="border border-white border-2 rounded-3 fill-color-bg">
        <a href="https://cloud.nakkefestival.dk/apps/collectives/" class="fill-div">
          <p class="text-center bello h3 mt-2">
            Wiki
          </p>
        </a>
      </div>
    </div>
  {% endif %}
  {% if perms.year.access_cloud %}
    <div class="col-3 mt-1 pt-1">
      <div class="border border-white border-2 rounded-3 fill-color-bg">
        <a href="https://cloud.nakkefestival.dk" class="fill-div">
          <p class="text-center bello h3 mt-2">
            Cloud
          </p>
        </a>
      </div>
    </div>
  {% endif %}
  {% if perms.year.view_ticket %}
    <div class="col-3 mt-1 pt-1">
      <div class="border border-white border-2 rounded-3 fill-color-bg">
        <a href="https://place2book.com/da/dashboard" class="fill-div">
          <p class="text-center bello h3 mt-2">
            Billetter
          </p>
        </a>
      </div>
    </div>
  {% endif %}
  {% if perms.year.access_chat %}
    <div class="col-3 mt-1 pt-1">
      <div class="border border-white border-2 rounded-3 fill-color-bg">
        <a href="https://cloud.nakkefestival.dk/apps/spreed/" class="fill-div">
          <p class="text-center bello h3 mt-2">
            Chat
          </p>
        </a>
      </div>
    </div>
  {% endif %}
  {% if perms.year.access_mail %}
    <div class="col-3 mt-1 pt-1">
      <div class="border border-white border-2 rounded-3 fill-color-bg">
        <a href="#" class="fill-div">
          <p class="text-center bello h3 mt-2">
            Mail
          </p>
        </a>
      </div>
    </div>
  {% endif %}
</div>
{% endblock page_content %}

src/year/templates/hzd/layout.html
<!DOCTYPE html>
{% load year_tags %}
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_DEV|add:"bootstrap5/css/bootstrap.min.css" }}">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_DEV|add:"fonts/fontawesome/css/all.min.css" }}">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_DEV|add:"css/main.css" }}">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="shortcut icon" href="{{ STATIC_DEV|add:"favicon.ico" }}">

    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-3.4.0.min.js"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

    <style>
    .clickable-row {
        cursor: pointer;
    }
    .table-hover tr:hover {
        background-color: rgba(0, 190, 255, 0.3); /* Adjust the color and opacity as needed */
    }
    </style>

    <script>
    document.addEventListener("DOMContentLoaded", function() {
      const rows = document.querySelectorAll("tr[data-href]");
      rows.forEach(row => {
        row.addEventListener("click", function() {
          window.location.href = this.getAttribute("data-href");
        });
      });
    });
    </script>

    {% if title %}
      <title>Nakkefestival - {{ title }}</title>
    {% else %}
      <title>Nakkefestival</title>
    {% endif %}

</head>
<body style="min-height:100vh; display:flex; flex-direction:column">
  <nav class="navbar navbar-expand-sm navbar-light bg-light py-0 fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand bello" href="{% url 'hzd:index' %}">HZD</a>
      <a class="navbar-brand" href="https://www.instagram.com/nakkefestival/"><i class="fa-brands fa-instagram"></i></a>
      <a class="navbar-brand" href="https://www.facebook.com/OfficielNakkefestival/"><i class="fa-brands fa-facebook"></i></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          {% if perms.year.view_program or perms.year.view_event or perms.year.view_artistapplication or perms.year.view_artist %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle h4 bello mb-0" href="#" id="programDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Program
            </a>
            <ul class="dropdown-menu" aria-labelledby="programDropdown">
              {% if perms.year.view_program %}
              <li>
                <a class="dropdown-item bello" href="{% url 'hzd:programs' year=current_year %}">Program</a>
              </li>
              {% endif %}
              {% if perms.year.view_event %}
              <li>
                  <a class="dropdown-item bello" href="{% url 'hzd:events' %}">Events</a>
              </li>
              {% endif %}
              {% if perms.year.view_artistapplication %}
              <li>
                  <a class="dropdown-item bello" href="{% url 'hzd:bookings' year=current_year %}">Bookings</a>
              </li>
              {% endif %}
              {% if perms.year.view_artist %}
              <li>
                  <a class="dropdown-item bello" href="{% url 'hzd:artists' %}">Kunstnere</a>
              </li>
              {% endif %}
            </ul>
          </li>
          {% endif %}
          {% if perms.year.view_volunteerarea or perms.year.view_volunteerapplication %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle h4 bello mb-0" href="#" id="volunteerDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Frivillige
              </a>
              <ul class="dropdown-menu" aria-labelledby="volunteerDropdown">
                {% if perms.year.view_volunteerarea %}
                  <li>
                      <a class="dropdown-item bello" href="{% url 'hzd:areas' year=current_year %}">Områder</a>
                  </li>
                {% endif %}
                {% if perms.year.view_volunteerapplication %}
                  <li>
                      <a class="dropdown-item bello" href="{% url 'hzd:volunteers' year=current_year %}">Frivillige</a>
                  </li>
                {% endif %}
              </ul>
            </li>
          {% endif %}
          {% if perms.year.view_donation or perms.year.view_page or perms.year.view_year %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle h4 bello mb-0" href="#" id="manageDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Organisation
              </a>
              <ul class="dropdown-menu" aria-labelledby="volunteerDropdown">
                {% if perms.year.view_donation %}
                  <li>
                      <a class="dropdown-item bello" href="{% url 'hzd:donations' %}">Donationer</a>
                  </li>
                {% endif %}
                {% if perms.year.view_page %}
                  <li>
                      <a class="dropdown-item bello" href="{% url 'hzd:pages' %}">Sider</a>
                  </li>
                {% endif %}
                {% if perms.year.view_year %}
                  <li>
                      <a class="dropdown-item bello" href="{% url 'hzd:years' %}">År</a>
                  </li>
                {% endif %}
              </ul>
            </li>
          {% endif %}
          <li class="nav-item" style="margin-right:2rem;">
              <a class="nav-link  h4 bello mb-0" href="{% url 'year:index' %}"><i class="bi bi-house"></i></a>
          </li>
          <li class="nav-item dropdown" style="margin-right:2rem;">
            <a class="nav-link dropdown-toggle h4 bello mb-0" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="true">
              <i class="fa-solid fa-circle-user"></i>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              {% if user.is_authenticated %}
                <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">Profil</a></li>
                {% if perms.year.view_hzd %}
                  <li><a class="dropdown-item" href="{% url 'hzd:index' %}">Hzd</a></li>
                {% endif %}
              <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Log af</a></li>
              {% else %}
                <li><a class="dropdown-item" href="{% url 'accounts:login' %}?role=guest">Log ind</a></li>
                 <li><a class="dropdown-item" href="{% url 'accounts:signup' %}?role=guest">Opret profil</a></li>               <li><a class="dropdown-item" href="{% url 'accounts:signup' %}">Opret profil</a></li>
              {% endif %}
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
    {% block content %}{% endblock %}
    <!-- JavaScript -->
    <!-- <script src="{{ STATIC_DEV|add:"bootstrap5/js/bootstrap.bundle.min.js" }}"></script> -->
</body>
</html>