src/hzd/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views 

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('aar/', views.YearView.as_view(), name='years'),
    path('aar/opret/', views.YearCreate.as_view(), name='year_create'),
    path('aar/tilpas/<int:pk>/', views.YearEdit.as_view(), name='year'),
    path('aar/slet/<int:pk>/', views.YearDeleteView.as_view(), name='year_delete'),
    path('booking/<int:year>/', views.BookingView.as_view(), name='bookings'),
    path('booking/opret/', views.BookingCreate.as_view(), name='booking_create'),
    path('booking/tilpas/<int:pk>/', views.BookingEdit.as_view(), name='booking'),
    path('booking/slet/<int:pk>/', views.BookingDeleteView.as_view(), name='booking_delete'),
    path('frivillige/<int:year>/', views.VolunteerView.as_view(), name='volunteers'),
    path('frivillige/opret/', views.VolunteerCreate.as_view(), name='volunteer_create'),
    path('frivillige/tilpas/<int:pk>/', views.VolunteerEdit.as_view(), name='volunteer'),
    path('frivillige/slet/<int:pk>/', views.VolunteerDeleteView.as_view(), name='volunteer_delete'),
    path('sider/', views.PageView.as_view(), name='pages'),
    path('sider/tilpas/<int:pk>/', views.PageEdit.as_view(), name='page'),
    path('sider/slet/<int:pk>/', views.PageDeleteView.as_view(), name='page_delete'),
    path('donationer/', views.DonationView.as_view(), name='donations'),
    path('donationer/opret/', views.DonationCreate.as_view(), name='donation_create'),
    path('donationer/tilpas/<int:pk>/', views.DonationEdit.as_view(), name='donation'),
    path('donationer/slet/<int:pk>/', views.DonationDeleteView.as_view(), name='donation_delete'),
    path('events/', views.EventView.as_view(), name='events'),
    path('events/create/', views.EventCreate.as_view(), name='event_create'),
    path('events/tilpas/<int:pk>/', views.EventEdit.as_view(), name='event'),
    path('events/slet/<int:pk>/', views.EventDeleteView.as_view(), name='event_delete'),
    path('kunstnere/', views.ArtistView.as_view(), name='artists'),
    path('kunstnere/opret/', views.ArtistCreate.as_view(), name='artist_create'),
    path('kunstnere/slet/<int:pk>/', views.ArtistDeleteView.as_view(), name='artist_delete'),
    path('kunstnere/tilpas/<int:pk>/', views.ArtistEdit.as_view(), name='artist'),
    path('kunstnere/profil/<int:pk>', views.ArtistProfileView.as_view(), name='artist_profile'),
    path('program/<int:year>/', views.ProgramView.as_view(), name='programs'),
    path('program/opret/', views.ProgramCreate.as_view(), name='program_create'),
    path('program/tilpas/<int:pk>/', views.ProgramEdit.as_view(), name='program'),
    path('program/slet/<int:pk>/', views.ProgramDeleteView.as_view(), name='program_delete'),
    path('omraader/<int:year>/', views.VolunteerAreaView.as_view(), name='areas'),
    path('omraader/opret/', views.VolunteerAreaCreate.as_view(), name='area_create'), 
    path('omraader/opret/<int:pk>', views.VolunteerAreaCreate.as_view(), name='area_create_with_id'), 
    path('omraader/tilpas/<int:pk>/', views.VolunteerAreaEdit.as_view(), name='area'), 
    path('omraader/slet/<int:pk>/', views.VolunteerAreaDeleteView.as_view(), name='area_delete'), 
    path('mails/', views.MailView.as_view(), name='mails'), 
    path('mails/opret/', views.MailCreateView.as_view(), name='mail_create'), 
    path('mails/tilpas/<int:pk>/', views.MailEditView.as_view(), name='mail'), 
    path('mails/slet/<int:pk>/', views.MailDeleteView.as_view(), name='mail_delete'), 
    path('send_mail/', views.SendMailView.as_view(), name='send_mail'), 
    path('vagter/<int:area>', views.VolunteerShiftView.as_view(), name='shifts'), 
    path('vagter/opret/', views.VolunteerShiftCreateView.as_view(), name='shift_create'), 
    path('vagter/tilpas/<int:pk>/', views.VolunteerShiftEditView.as_view(), name='shift'), 
    path('vagter/slet/<int:pk>/', views.VolunteerShiftDeleteView.as_view(), name='shift_delete'), 
    path('save-shift-assignments/', views.save_shift_assignments, name='save_shift_assignments'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/nakkefestival/urls.py
from django.contrib import admin
from django.urls import include, path
from ckeditor_uploader import views as ckeditor_views

urlpatterns = [
    path("", include(("year.urls", "year"), namespace="year")),
    path("hzd/", include(("hzd.urls", "hzd"), namespace="hzd")),
    path("admin/", admin.site.urls),
    path("profil/", include(("accounts.urls", "accounts"), namespace="accounts")),  # new
    path("profil/", include("django.contrib.auth.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('openid/', include('oidc_provider.urls', namespace='oidc_provider')),
]

src/year/urls.py
from django.urls import path

from django.conf.urls import handler403
from . import views

app_name = "year"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('information/praktisk_information', views.Praktisk_informationView.as_view(), name='praktisk_information'),
    path('information/bliv_frivillig', views.Bliv_frivilligView.as_view(), name='bliv_frivillig'),
    path('information/bliv_kunstner', views.Bliv_kunstnerView.as_view(), name='bliv_kunstner'),
    path('information/fallesbus_til_nakke', views.Fallesbus_til_nakkeView.as_view(), name='fællesbus_til_nakke'),
    path('om/om_nakkefestival', views.Om_nakkefestivalView.as_view(), name='om_nakkefestival'),
    path('om/historien', views.HistorienView.as_view(), name='historien'),
    path('om/find_vej', views.Find_vejView.as_view(), name='find_vej'),
    path('om/billeder', views.BillederView.as_view(), name='billeder'),
    path('om/donationer', views.DonationerView.as_view(), name='donationer'),
    path('om/vedtagter', views.VedtagterView.as_view(), name='vedtagter'),
    path('om/presse', views.PresseView.as_view(), name='presse'),
    path('om/kontakt', views.KontaktView.as_view(), name='kontakt'),
    path('musik/kunstnere/<int:year>/', views.KunstnereView.as_view(), name='kunstnere'),
    # path('musik/kunstnere/<int=year>', views., name=''),
    # path('musik/kunstnere/<slug=band>', view., name''),
    path('musik/program/<int:year>/', views.ProgramView.as_view(), name='program'),
    # path('<int:year>?/musik/program', views.ProgramView.as_view(), name='program'),
    path('musik/events/<int:year>/', views.EventsView.as_view(), name='events'),
    path('kunstner_tilmelding/', views.SendApplicationView.as_view(), name='send_application'),
    path('om/privatlivspolitik/', views.PrivacyView.as_view(), name='privacy'),
] 


handler403 = views.CustomPermissionDeniedView.as_view()

src/hzd/models.py
from django.db import models

# Create your models here.

src/hzd/views.py
import logging
from django.contrib.auth.models import Group
from django.views.generic import TemplateView, ListView, DetailView, UpdateView, CreateView, DeleteView, FormView 
from django.views import View
# from django.views.generic.edit import UpdateView
from django.utils import timezone
from django.shortcuts import redirect, get_object_or_404 
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from . import urls 
from accounts.models import User, Committee, Mail
from accounts.services import send_template_email
from year.models import (Year, 
                        Page, 
                        ArtistApplication,
                        ApplicationStatus,
                        VolunteerApplication, 
                        Donation, 
                        Event, 
                        Artist, 
                        Program, 
                        VolunteerArea,
                        VolunteerShift)
from .forms import (YearForm,
                    YearCreateForm,
                    PageForm, 
                    ArtistApplicationForm,
                    ArtistApplicationCreateForm,
                    VolunteerApplicationForm, 
                    VolunteerApplicationCreateForm, 
                    DonationForm, 
                    DonationCreateForm,
                    EventForm, 
                    EventCreateForm, 
                    ArtistForm,
                    ArtistCreateForm,
                    ProgramForm,
                    ProgramCreateForm,
                    VolunteerAreaForm,
                    VolunteerAreaCreateForm,
                    MailForm,
                    MailCreateForm,
                    SendMailForm,
                    VolunteerShiftCreateForm,
                    VolunteerShiftEditForm)
from .bokeh_plots import index_volunteer, index_sales, donations_plot
from django.core.mail import send_mail, BadHeaderError, EmailMessage
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
from django.contrib.auth.decorators import login_required, permission_required
from collections import defaultdict
from datetime import date, datetime
from django.db.models import Q 

logger = logging.getLogger(__name__) # Configure logging

class SendMailView(LoginRequiredMixin, PermissionRequiredMixin, FormView):
    login_url = "/profil/log-ind/"
    redirect_field_name = "redirect_to"
    template_name = "hzd/send_mail.html"
    form_class = SendMailForm
    permission_required = 'accounts.send_mail'
    
    def form_valid(self, form):
        # Process the form and send email
        sender = form.cleaned_data['sender']
        receiver = form.cleaned_data['receiver']
        template = form.cleaned_data['template']
        title = form.cleaned_data['title']
        message = form.cleaned_data.get('message', '')
        link = form.cleaned_data['link']
        link_label = form.cleaned_data['link_label']
         
        sender_email = sender.mail # Assign the email of the selected volunteer area

        # Assign the receiver list
        receiver_list = receiver.split(';')
        print(f"mailId: {template.id}")
        for email in receiver_list:
            print(f"address: {email}")
            if email.find('@'):
                try:
                    user = User.objects.get(email=email)
                    send_template_email(
                        user=user,
                        mailId=template.id,
                        link_url=link or template.link,
                        message=message,
                        title=title,
                        link_label=link_label
                    )
                    print(f"Email sent to {user}!")
                except Exception as e:
                    # Log or print the actual error message
                    print(f"Error sending email: {e}")
        
        return super().form_valid(form)

    def get_success_url(self):
#        next_url = self.request.GET.get('next')
#        if next_url:
        cur_year = Year.current_year()
        return reverse_lazy('hzd:volunteers', kwargs={'year': cur_year})

    def get_context_data(self, **kwargs):
        context = super(SendMailView, self).get_context_data(**kwargs)
        page = Page.objects.get(id=45)
        context['title'] = page.title
        context['bg'] = page.bg_image
        context['submit_button'] = 'Send mail'

        # Load form data for preview
        form = self.get_form()  # Get the form instance
        
        mail_template = form.fields['template'].initial  # Get the initial Mail template object
        if mail_template:
            short_description = mail_template.short_description
            long_description = mail_template.long_description
            link_url = mail_template.link
        else:
            short_description = "Din emnetitel her"
            long_description = ""
            link_url = 'Dit link her'

        # Pass preview data into the context
        preview_data = {
            'user': {'first_name': 'John Doe'},  # Static user data for preview purposes
            'short_description': self.request.POST.get('title', short_description),
            'long_description': self.request.POST.get('message', long_description),
            'message': self.request.POST.get('message', 'Din besked her'),
            'link_url': self.request.POST.get('link', link_url),
            'button_label': self.request.POST.get('link_label', ''),
            'current_year': Year.current_year(),
        }

        context['preview_data'] = preview_data
        return context

    def get_sender(self):
        sender_id = self.request.GET.get('sender_id') 
        if sender_id:
            try:
                area = VolunteerArea.objects.get(id=sender_id)
                if area.mail:
                    return area.mail
            except VolunteerArea.DoesNotExist:
                pass
        return None

    def get_receivers(self):
        receiver_set = set()  # Use a set to automatically handle duplicates

        # Add mail for the user with a supplied user_id
        user_id = self.request.GET.get('user_id')
        if user_id:
            try:
                user_mail = User.objects.get(id=user_id).email
                if user_mail:
                    receiver_set.add(user_mail)  # Add to set
            except User.DoesNotExist:
                pass

        # Add all emails that users in a supplied group_id
        group_id = self.request.GET.get('group_id')
        if group_id:
            try:
                group = Group.objects.get(id=group_id)
                group_mails = User.objects.filter(groups=group).values_list('email', flat=True)
                receiver_set.update(group_mails)  # Add all to set
            except Group.DoesNotExist:
                pass

        # Add all emails of users associated with the artist
        artist_id = self.request.GET.get('artist_id')
        if artist_id:
            try:
                artist = Artist.objects.get(id=artist_id)
                artist_mails = User.objects.filter(artists=artist).values_list('email', flat=True)
                receiver_set.update(artist_mails)  # Add all to set
            except Artist.DoesNotExist:
                pass

        # Add all emails of users associated with the area
        area_id = self.request.GET.get('area_id')
        if area_id:
            try:
                area = VolunteerArea.objects.get(id=area_id)
                current_year = Year.current_year()
                applications = VolunteerApplication.objects.filter(
                    area=area,
                    year=current_year,
                    status=2
                )
                area_mails = User.objects.filter(volunteer_application__in=applications).values_list('email', flat=True)
                receiver_set.update(area_mails)  # Add all to set
            except VolunteerArea.DoesNotExist:
                pass

        # Return joined list if not empty
        return ';'.join(receiver_set) if receiver_set else None

    def get_template(self):
        template_id = self.request.GET.get('template_id')
        if template_id:
            try:
                template = Mail.objects.get(id=template_id)
                return template
            except Mail.DoesNotExist:
                pass
        return None

    def get_form_kwargs(self):
        kwargs = super(SendMailView, self).get_form_kwargs()
        kwargs.update({
            'sender': self.get_sender(),
            'receiver': self.get_receivers(),
            'template': self.get_template(),
        })
        return kwargs

class IndexView(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    login_url = "/profil/log-ind/"
    redirect_field_name = "redirect_to"

    template_name = "hzd/index.html"
    permission_required = 'year.view_hzd'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        script, div = index_volunteer()
        context['bokeh_script'] = script
        context['bokeh_div'] = div

        script2, div2 = index_sales()
        context['bokeh_script2'] = script2
        context['bokeh_div2'] = div2

        context['title'] = Page.objects.get(id=16).title
        context['bg'] = Page.objects.get(id=16).bg_image
        
        return context

class YearView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    login_url = "/profil/log-ind/"
    redirect_field_name = "redirect_to"

    template_name = "hzd/year/index.html"
    context_object_name = 'years'
    permission_required = 'year.view_year'
   
    def get_queryset(self):
        # Get the sorting parameter from the request
        sort_by = self.request.GET.get('sort', '-year')

src/year/templates/hzd/program/index.html
{% extends "year/page.html" %}
{% block page_content %}

<div class="row d-flex justify-content-center">
  <div class="col-5 text-center">
    <a class="btn btn-primary mx-auto" href="{% url 'hzd:events' %}">Events</a>
    <a class="btn btn-primary mx-auto" href="{% url 'hzd:artists' %}">Kunstnere</a>
    <a class="btn btn-primary mx-auto" href="{% url 'hzd:bookings' year=current_year %}">Bookings</a>
  </div>
</div>

<div class="row mb-3">
  <div class="dropdown bello text-center">
    <button class="btn opacity-25 dropdown-toggle" style="font-size:2rem;" type="button" id="dropdownSelectButton" data-bs-toggle="dropdown" aria-expanded="false">
      <b style="font-size:3rem">{{ year }}</b> 
    </button>
    <ul class="dropdown-menu scroller" aria-labelledby="dropdownSelectButton" style="max-height:15rem;overflow-y:scroll;">
      {% for year_obj in every_year %}
        <li class="dropdowm-item ">
          <a class="dropdown-item d-block" href="{% url 'hzd:programs' year=year_obj.year %}">{{ year_obj.year }}</a> 
        </li>
      {% endfor %}
    </ul>
  </div>
</div>

<div class="d-flex justify-content-end mb-3">
  <a class="btn btn-primary" href="{% url 'hzd:program_create' %}?next={{ request.path }}"><i class="fa fa-plus-circle" aria-hidden="true"> Opret Begivenhed</i></a>
</div>

{% if program %}
<div class="table-container mt-3">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th class="d-none d-sm-table-cell"> 
            <a class="btn btn-primary" href="?sort=year&order=
              {% if current_sort == 'year' and next_order == 'asc' %}
                asc
              {% else %}
                desc
              {% endif %}">
                År
            </a>
        </th>
        <th>
            <a class="btn btn-primary" href="?sort=artist_id&order={% if current_sort == 'artist_id' and next_order == 'asc' %}asc{% else %}desc{% endif %}">
              <b>Artist</b>
            </a>
        </th>
        <th>
            <a class="btn btn-primary" href="?sort=event_id&order={% if current_sort == 'event_id' and next_order == 'asc' %}asc{% else %}desc{% endif %}">
              <b>Event</b>
            </a>
        </th>
        <th class="d-none d-sm-table-cell">
            <a class="btn btn-primary" href="?sort=start_time&order={% if current_sort == 'start_time' and next_order == 'asc' %}asc{% else %}desc{% endif %}">
                Starttid
            </a>
        </th>
        <th class="d-none d-sm-table-cell">
            <a class="btn btn-primary" href="?sort=end_time&order={% if current_sort == 'end_time' and next_order == 'asc' %}asc{% else %}desc{% endif %}">
                Sluttid
            </a>
        </th>
        <th class="d-none d-sm-table-cell">
            <a class="btn btn-primary" href="?sort=stage&order={% if current_sort == 'stage' and next_order == 'asc' %}asc{% else %}desc{% endif %}">
                Scene
            </a>
        </th>
        <th class="d-none d-sm-table-cell">
            <a class="btn btn-primary" href="?sort=published&order={% if current_sort == 'published' and next_order == 'asc' %}asc{% else %}desc{% endif %}">
                Udgivet
            </a>
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for p in program %}
        <tr class="clickable-row"  data-href="{% url 'hzd:program' pk=p.pk %}?next={{ request.path }}">
          <td class="d-none d-sm-table-cell">{{ p.year }}</td>
          <td>
            {% if p.artist %}
              <a href="{% url 'hzd:artist' pk=p.artist.pk %}?next={{ request.path }}" class="link-success">
                <b>{{ p.artist }}</b>
              </a>
            {% endif %}
          </td>
          <td>
            {% if p.event %}
              <a href="{% url 'hzd:event' pk=p.event.pk %}?next={{ request.path }}" class="link-success">
                <b>{{ p.event }}</b>
              </a>
            {% endif %}
          </td>
          <td class="d-none d-sm-table-cell">{{ p.start_time }}</td>
          <td class="d-none d-sm-table-cell">{{ p.end_time }}</td>
          <td class="d-none d-sm-table-cell">{{ p.stage }}</td>
          <td class="d-none d-sm-table-cell">{{ p.published }}</td>
          <td>
            <a href="{% url 'hzd:program' pk=p.pk %}?next={{ request.path }}"><i class="bi bi-pencil-square"></i></a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% else %}
  <p>There are no pages to be displayed.</p>
{% endif %}
{% endblock page_content %}

src/year/templates/hzd/program/program.html
{% extends "year/page.html" %}
{% block page_content %}

<div styl="background-image: url('{{ bg.image_url }}');">
    <!-- Include the reusable form template -->
    {% include 'form_snippet.html' with form=form method='post' action='' button_label='Opdater' %}
</div>

<!-- Delete Modal -->
{% if button_label_delete %}
  <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" style="min-width:50vw;">
      <div class="modal-content" style="background-size:cover; background-image:url('{{ STATIC_DEV|add:"img/bg/home.jpg" }}');">
        <div class="modal-header">
          <h1 class="modal-title bello" id="exampleModalLabel">Slet</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Er du sikker?</p>
        </div>
        <div class="modal-footer">
          <form method="post" action="{% url 'hzd:program_delete' program_edit.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Slet det</button>
          </form>
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal" aria-label="Close">
            <p>Fortryd</p>
          </button>
        </div>
      </div>
    </div>
  </div>
{% endif %}

{% endblock page_content %}