src/accounts/urls.py
#!/usr/bin/env python3

from django.urls import path
from .views import SignupView, LoginView, LogoutView, AuthStatusView, ProfileView, ProfileEditView, ProfileDeleteView, ResetPasswordView, UserView, verify_email, SendSignInEmail, EmailSentView, ForgottenPasswordView, PasswordResetRequestView, SetNotificationsView, ApplicationSentView

urlpatterns = [
    path('opret/', SignupView.as_view(), name='signup'),
    path('log-ind/', LoginView.as_view(), name='login'),
    path('log-ud/', LogoutView.as_view(), name='logout'),
    path('auth-status/', AuthStatusView.as_view(), name='auth_status'),
    path('ret/', ProfileEditView.as_view(), name='profile_edit'),
    path('slet/', ProfileDeleteView.as_view(), name='profile_delete'),
    path('', ProfileView.as_view(), name='profile'),
    path('skift-kode/', ResetPasswordView.as_view(), name='reset_password'),
    path('<int:pk>/', UserView.as_view(), name='user'),
    path('sign-in', SendSignInEmail.as_view(), name='sign_in'),
    path('verify-email/<uidb64>/<token>/', verify_email, name='verify_email'),
    path('tilmelding-sendt/<str:email>/', ApplicationSentView.as_view(), name='application_sent'),
    path('email-sendt/<int:pk>/', EmailSentView.as_view(), name='email_sent'),
    path('ny-kode/<uidb64>/<token>/', ForgottenPasswordView.as_view(), name='forgotten_password'),
    path('ny-kode/', PasswordResetRequestView.as_view(), name='reset_request'),
    path('notifikationer/', SetNotificationsView.as_view(), name='notifications'),
]

src/hzd/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views 

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('aar/', views.YearView.as_view(), name='years'),
    path('aar/opret/', views.YearCreate.as_view(), name='year_create'),
    path('aar/tilpas/<int:pk>/', views.YearEdit.as_view(), name='year'),
    path('aar/slet/<int:pk>/', views.YearDeleteView.as_view(), name='year_delete'),
    path('booking/<int:year>/', views.BookingView.as_view(), name='bookings'),
    path('booking/opret/', views.BookingCreate.as_view(), name='booking_create'),
    path('booking/tilpas/<int:pk>/', views.BookingEdit.as_view(), name='booking'),
    path('booking/slet/<int:pk>/', views.BookingDeleteView.as_view(), name='booking_delete'),
    path('frivillige/<int:year>/', views.VolunteerView.as_view(), name='volunteers'),
    path('frivillige/opret/', views.VolunteerCreate.as_view(), name='volunteer_create'),
    path('frivillige/tilpas/<int:pk>/', views.VolunteerEdit.as_view(), name='volunteer'),
    path('frivillige/slet/<int:pk>/', views.VolunteerDeleteView.as_view(), name='volunteer_delete'),
    path('sider/', views.PageView.as_view(), name='pages'),
    path('sider/tilpas/<int:pk>/', views.PageEdit.as_view(), name='page'),
    path('sider/slet/<int:pk>/', views.PageDeleteView.as_view(), name='page_delete'),
    path('donationer/', views.DonationView.as_view(), name='donations'),
    path('donationer/opret/', views.DonationCreate.as_view(), name='donation_create'),
    path('donationer/tilpas/<int:pk>/', views.DonationEdit.as_view(), name='donation'),
    path('donationer/slet/<int:pk>/', views.DonationDeleteView.as_view(), name='donation_delete'),
    path('events/', views.EventView.as_view(), name='events'),
    path('events/create/', views.EventCreate.as_view(), name='event_create'),
    path('events/tilpas/<int:pk>/', views.EventEdit.as_view(), name='event'),
    path('events/slet/<int:pk>/', views.EventDeleteView.as_view(), name='event_delete'),
    path('kunstnere/', views.ArtistView.as_view(), name='artists'),
    path('kunstnere/opret/', views.ArtistCreate.as_view(), name='artist_create'),
    path('kunstnere/slet/<int:pk>/', views.ArtistDeleteView.as_view(), name='artist_delete'),
    path('kunstnere/tilpas/<int:pk>/', views.ArtistEdit.as_view(), name='artist'),
    path('kunstnere/profil/<int:pk>', views.ArtistProfileView.as_view(), name='artist_profile'),
    path('program/<int:year>/', views.ProgramView.as_view(), name='programs'),
    path('program/opret/', views.ProgramCreate.as_view(), name='program_create'),
    path('program/tilpas/<int:pk>/', views.ProgramEdit.as_view(), name='program'),
    path('program/slet/<int:pk>/', views.ProgramDeleteView.as_view(), name='program_delete'),
    path('omraader/<int:year>/', views.VolunteerAreaView.as_view(), name='areas'),
    path('omraader/opret/', views.VolunteerAreaCreate.as_view(), name='area_create'), 
    path('omraader/opret/<int:pk>', views.VolunteerAreaCreate.as_view(), name='area_create_with_id'), 
    path('omraader/tilpas/<int:pk>/', views.VolunteerAreaEdit.as_view(), name='area'), 
    path('omraader/slet/<int:pk>/', views.VolunteerAreaDeleteView.as_view(), name='area_delete'), 
    path('mails/', views.MailView.as_view(), name='mails'), 
    path('mails/opret/', views.MailCreateView.as_view(), name='mail_create'), 
    path('mails/tilpas/<int:pk>/', views.MailEditView.as_view(), name='mail'), 
    path('mails/slet/<int:pk>/', views.MailDeleteView.as_view(), name='mail_delete'), 
    path('send_mail/', views.SendMailView.as_view(), name='send_mail'), 
    path('vagter/<int:area>', views.VolunteerShiftView.as_view(), name='shifts'), 
    path('vagter/opret/', views.VolunteerShiftCreateView.as_view(), name='shift_create'), 
    path('vagter/tilpas/<int:pk>/', views.VolunteerShiftEditView.as_view(), name='shift'), 
    path('vagter/slet/<int:pk>/', views.VolunteerShiftDeleteView.as_view(), name='shift_delete'), 
    path('save-shift-assignments/', views.save_shift_assignments, name='save_shift_assignments'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/nakkefestival/urls.py
from django.contrib import admin
from django.urls import include, path
from ckeditor_uploader import views as ckeditor_views

urlpatterns = [
    path("", include(("year.urls", "year"), namespace="year")),
    path("hzd/", include(("hzd.urls", "hzd"), namespace="hzd")),
    path("admin/", admin.site.urls),
    path("profil/", include(("accounts.urls", "accounts"), namespace="accounts")),  # new
    path("profil/", include("django.contrib.auth.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('openid/', include('oidc_provider.urls', namespace='oidc_provider')),
]

src/year/models.py
from django.db import models
from accounts.models import User
from django.utils import timezone
from django.contrib.postgres.fields import ArrayField
from ckeditor.fields import RichTextField
from datetime import datetime, time, timedelta
from django.db.models.signals import m2m_changed
from django.dispatch import receiver

class Year(models.Model):
    year = models.IntegerField()
    published = models.BooleanField(default=False)
    start_time = models.DateTimeField(blank=True)
    end_time = models.DateTimeField(blank=True)
    banner_image = models.ImageField(upload_to='images/year/', blank=True)
    
    @classmethod
    def current_year(cls):
        # Set year object to the next year, if only 120 days from next year
        offset_date=timezone.now()+timedelta(days=120)
        offset_year=offset_date.year

        # return year object with offset year
        return cls.objects.get_or_create(year=offset_year)[0]

    def __str__(self):
        return str(self.year)

    class Meta:
        permissions = [
            ("view_hzd", "Can view Hzd"),
            ("access_wiki", "Can access Wiki"),
            ("access_cloud", "Can access Cloud drive"),
            ("access_chat", "Can access Chat"),
            ("access_mail", "Can access Mail"),
        ]

class Page(models.Model):
    year = models.ForeignKey(Year, on_delete=models.CASCADE)
    
    title = models.CharField(max_length=50)
    bg_image = models.ImageField(upload_to='images/pages/', blank=True)
    short_description = models.CharField(max_length=500, blank=True)
    long_description = RichTextField(blank=True)
    organiser_page = models.BooleanField(default=False)
    
    def __str__(self):
        """
        How the record is represented in the django admin interface
        """
        return self.title

class Donation(models.Model):
    year = models.ForeignKey(Year, on_delete=models.CASCADE, related_name='donations')
    
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    receiver = models.CharField(max_length=50)
    published = models.BooleanField(default=False)
    phone = models.CharField(max_length=50, blank=True)
    mail = models.EmailField(blank=True)
    link = models.URLField(blank=True)

    def __str__(self):
        return f'{self.year} - {self.amount} kr.'
    
class Event(models.Model):
    name = models.CharField(max_length=50)
    # img = models.CharField(max_length=250, blank=True)
    short_description = models.CharField(max_length=250, blank=True)
    long_description = RichTextField(max_length=2500, blank=True)
    img = models.ImageField(upload_to='images/events/', blank=True)
    # state = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Artist(models.Model):
    name = models.CharField(max_length=100)
    short_description = models.CharField(max_length=500, blank=True)
    long_description = RichTextField(blank=True, max_length=2500)
    img = models.ImageField(upload_to='images/artists/', blank=True)
    # mp3 = models.CharField(max_length=50, blank=True)
    link_youtube = models.URLField(blank=True)
    link_spotify = models.URLField(blank=True)
    link_soundcloud = models.URLField(blank=True)
    link_bandcamp = models.URLField(blank=True)
    link_other = models.URLField(blank=True)
    user = models.ManyToManyField(User, related_name='artists')
    # state = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        permissions = (
            ('view_allartists', "Can view all artists"),
        )

# Signal handler for ManyToMany field changes on `user`
@receiver(m2m_changed, sender=Artist.user.through)
def delete_artist_if_no_users(sender, instance, action, **kwargs):
    if action == "post_remove":  # Trigger after users are removed
        if instance.user.count() == 0:  # Check if no users remain
            instance.delete()  # Delete the Artist instance

class Stage(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Program(models.Model):
    year = models.ForeignKey(Year, on_delete=models.CASCADE, related_name='programs')
    stage = models.ForeignKey(Stage, on_delete=models.CASCADE, related_name='programs')
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, related_name='programs', blank=True, null=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='programs', blank=True, null=True)

    start_time = models.DateTimeField()
    end_time = models.DateTimeField(null=True,blank=True)
    published = models.BooleanField(default=False)
    
    def __str__(self):
        if self.artist_id: 
            return f'{self.year} - {self.artist_id}'
        else: 
            return f'{self.year} - {self.event_id}'

class ApplicationStatus(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class ArtistApplication(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, related_name='artist_applications')
    year = models.ForeignKey(Year, on_delete=models.CASCADE, related_name='artist_applications')
    time = models.DateTimeField(auto_now_add=True)
    techrider = models.FileField(upload_to='techriders/', blank=True)
    user_comment = models.TextField(blank=True)

    status = models.ForeignKey(ApplicationStatus, on_delete=models.CASCADE, related_name='artist_applications')
    org_comment = RichTextField(blank=True)
    class Meta:
        permissions = (
            ('test_artistapplications', "Can test artist applications"),
            ('view_artistapplicationstatus','Can view artist application status'),
            ('change_artistapplicationstatus','Can change artist application status'),
            ('view_orgcomment', 'Can view artist application organiser comment'),
            ('change_orgcomment', 'Can change artist application organiser comment'),
        )

class Venue(models.Model):
    name = models.CharField(max_length=50)
    adress = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=16, blank=True)
    link = models.CharField(max_length=250, blank=True)

    def __str__(self):
        return self.name

class Concert(models.Model):
    time = models.DateTimeField()
    comment = RichTextField(max_length=250, blank=True)

    def __str__(self):
        return self.time

class Genre(models.Model):
    tag = models.CharField(max_length=50)

    def __str__(self):
        return self.tag

class ArtistManagement(models.Model):
    comment = models.TextField(max_length=250, blank=True)
    votes = models.IntegerField()
    stars = models.IntegerField()
    commentCount = models.IntegerField()

class VolunteerApplication(models.Model):
    year = models.ForeignKey(Year, on_delete=models.CASCADE, related_name='volunteer_application')
    time = models.DateTimeField(auto_now_add=True)
    area = models.ForeignKey("VolunteerArea", on_delete=models.CASCADE, related_name='volunteer_application')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='volunteer_application')
    user_comment = models.TextField(blank=True)
    manager = models.BooleanField(default=False) 
    status = models.ForeignKey(ApplicationStatus, on_delete=models.CASCADE, related_name='volunteer_application')
    org_comment = RichTextField(blank=True)

    def __str__(self):
        return f'{self.area} - {self.time}'
    
    class Meta:
        permissions = [
            ("view_volunteerapplicationstatus", "Can view volunteer application status"),
            ("change_volunteerapplicationstatus", "Can change volunteer application status"),
            ("view_orgcomment", "Can view organiser comment of volunteer application"),
            ("change_orgcomment", "Can change organiser comment of volunteer application"),
            ("change_volunteerapplicationarea", "Can change volunteer area for a volunteer application"),
        ]

class VolunteerArea(models.Model):
    year = models.ForeignKey(Year, on_delete=models.CASCADE, related_name='volunteer_area')
    name = models.CharField(max_length=50)
    published = models.BooleanField()
    mail = models.CharField(max_length=50, blank=True)
    volunteerCount = models.IntegerField(default=0)
    volunteerMax = models.IntegerField()
    managerCount = models.IntegerField(default=0)
    managerMax = models.IntegerField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    bg = models.ImageField(upload_to='images/areas/', blank=True)
    short_description = models.CharField(max_length=250, blank=True)
    long_description = RichTextField(max_length=10000, blank=True)

    def __str__(self):
        return self.name
    
    class Meta:
        permissions = [
            ("view_allareas", "Can view all volunteer areas"),
        ]
    
class TicketType(models.Model):
    year = models.ForeignKey(Year, on_delete=models.CASCADE, related_name='tickettype')
    name = models.CharField(max_length=50)
    price = models.CharField(max_length=50)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    description = models.CharField(max_length=500)
    stock = models.IntegerField()
    onlineSale = models.IntegerField()
    doorSale = models.IntegerField()
    published = models.BooleanField()

    def __str__(self):
        return f'{self.year} - {self.name}'
    
class Ticket(models.Model):
    ticketType = models.ForeignKey("TicketType", on_delete=models.CASCADE, related_name='ticket')
    purchase_date = models.DateField(max_length=50)

    def __str__(self):
        return f'{self.ticketType} - {self.purchase_date}'

class VolunteerShift(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='volunteershift', null=True, blank=True)
    area = models.ForeignKey(VolunteerArea, on_delete=models.CASCADE, related_name='volunteershift')

src/accounts/templates/accounts/application_sent.html
{% extends "year/page.html" %}
{% block page_content %}
{% endblock %}

src/accounts/templates/accounts/email_sent.html
{% extends "year/page.html" %}
{% block page_content %}
<div class="container">
  <p>Vi har sendt en engangskode til: <a href=mailto:{{ user.email }}>{{ user.email }}</a></p>
  <p>Du kan logge ind på vores hjemmeside gennem engangskoder, som vi sender til din email-adresse.</p>
</div>
{% endblock %}

src/accounts/templates/accounts/forgotten_password.html
{% extends "year/page.html" %}

{% block page_content %}
  <h2>{{ title }}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">{{ submit_button }}</button>
  </form>
{% endblock %}

src/accounts/templates/accounts/notifications.html
{% extends "year/page.html" %}
{% block page_content %}

<div styl="background-image: url('{{ bg.image_url }}');">
    <!-- Include the reusable form template -->
  <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Submit</button>
  </form>
</div>

{% endblock page_content %}

src/accounts/templates/accounts/password_reset_request.html
{% extends "year/page.html" %}
{% block page_content %}

<div class="d-flex justify-content-center" style="background-image: url('{{ bg.image_url }}');">
  <form class="col-lg-8" method="post">
      {% csrf_token %}
      <div class="form-group">
        <p>Indtast din email-adresse, og så sender vi dig et magic-link, som du kan gendanne din adgangskode igennem.</p>
        <input class="form-control" type="email" name="email" required>
      </div>
      <button class="btn btn-primary mt-3" type="submit">Send link til gendannelse</button>
      <a href="{% url 'accounts:login' %}" class="btn btn-secondary mt-3">Gå tilbage til login</a>
      {% if error %}
          <p style="color: red;">{{ error }}</p>
      {% endif %}
      {% for message in messages %}
          <p style="color: green;">{{ message }}</p>
      {% endfor %}
  </form>
</div>

{% endblock %}

src/accounts/templates/accounts/profile.html
{% extends "year/page.html" %}
{% block page_content %}

  {% if user.is_authenticated %}
    <div class="row d-flex justify-content-center">
      <!-- Profile Info -->
      <div class="col-sm-10 col-md-10 col-lg-10 row rounded" style="background-color: rgba(255, 255, 255, 0.5);">
        <div class="col-10 mt-3 mb-3">
          <h4 class="bello">{{ user.username }}</h4>
          <ul>
          <li>{{ user.phone }}</li>
          <li><a href="mailto:{{ user.email }}">{{ user.email }}</a></li>
          {% if volunteer_application %}
            <li><a href="{% url 'hzd:volunteer' pk=volunteer_application.pk %}?next={{ request.path }}">{{ area_name }}</a></li>
          {% elif artist_application %}
            <li><a href="{% url 'hzd:booking' pk=artist_application.pk %}?next={{ request.path }}">{{ artist_name }}</a></li>
          {% else %}
            <li>Du er ikke tilmeldt Nakkefestival {{ current_year }}</li>
          {% endif %}
        </div>
        <div class="col-2">
          <div>
            <img src="{% if user.img %} {{ user.img.url }} {% endif %}" class="img-fluid rounded-circle text-end" alt="Profile Image" style="max-width:100px;">
          </div>
          <div class="mt-10 text-end">
            <a href="{% url 'accounts:profile_edit' %}?next={{ request.path }}"><i class="bi bi-pencil-square"></i></a>
          </div>
        </div>
      </div>
    </div>
    <!-- Profile Actions -->
    <div class="row d-flex justify-content-center mt-5">
      <!-- Volunteer Application -->
      <div class="container rounded m-3 p-2" style="background-color: rgba(255, 255, 255, 0.5);">
        <div class="row">
          <div class="col">
            <h2 class="bello text-center">Tilmeldinger</h2>
          </div>
          <div class="col text-end">
            {% if any_open_areas %}
              {% if not has_current_year_volunteer_application %}
                <a class="btn btn-primary text-end" href="{% url 'hzd:volunteer_create' %}?next={{ request.path }}"><i class="fa fa-plus-circle" aria-hidden="true"> Opret</i></a>
              {% endif %}
            {% else %}
              <a class="btn btn-primary text-end disabled" href="{% url 'hzd:volunteer_create' %}?next={{ request.path }}"><i class="fa fa-plus-circle" aria-hidden="true"> Opret</i></a>
            {% endif %}
          </div>
        </div>
        <div class="container">
          {% for application in volunteer_applications %}
            <a class="btn w-100 mt-1 border border-1" href="#" data-bs-toggle="modal" data-bs-target="#modal{{ application.pk }}" style="background-color:{% if application.status_id == 1 %}#E0FFFF{% elif application.status_id == 2 %}#90EE90{% else  %}#F08080{% endif %}">
              <div class="row">
                <div class="col">
                  <h5>{{ application.area }}</h5>
                </div>
                <div class="col">
                  <p>{{ application.time }}</p>
                </div>
                <div class="col text-end">
                  <p>{{ application.status }}</p>
                </div>
              </div>
            </a>
          {% endfor %}
        </div>
      </div>
      <!-- Artist Application -->
<!--      <div class="container rounded m-3 p-2" style="background-color: rgba(255, 255, 255, 0.5);">
        <div class="row">
          <div class="col">  
            <h2 class="bello text-center">Kunstnerprofiler</h2>
          </div>
          <div class="col text-end">
            <a class="btn btn-primary" href="{% url 'hzd:artist_create' %}?next={{ request.path }}"><i class="fa fa-plus-circle" aria-hidden="true"> Opret</i></a>
          </div>
        </div>
        {% for artist in artists %}
          <div class="container border-rounded border-1 mt-2 d-flex align-items-start" style="background-color:#E0FFFF">
            {% if artist.id %}
              <div class="col-3">
                <img src="{% if artist.img %}{{ artist.img.url }}{% endif %}" class="img-fluid" alt="Artist Image" style="max-width: 100px;">
              </div>
              <div class="col-9">
                <div class="row">
                  <div class="col">
                    <a class="btn mt-1 border border-1" href="{% url 'hzd:artist' pk=artist.pk %}?next={{ request.path }}">
                      <h5>{{ artist }}</h5>
                    </a>
                  </div>
                  <div class="col text-end">
                    {% if not artist.has_current_year_application %}
                      <a class="btn btn-success" href="{% url 'hzd:booking_create' %}?next={{ request.path }}&artist_id={{ artist.id }}">
                        Ansøg
                      </a>
                    {% endif %}
                  </div>
                </div>
                {% if artist.artist_applications.all %}
                  <div class="row mt-2">
                    <ul class="list-group list-group-horizontal">
                      {% for application in artist.artist_applications.all %}
                        <li class="list-group-item w-100" style="background-color:#E0FFFF">
                          <a class="btn" href="{% url 'hzd:booking' pk=application.pk %}?next={{ request.path }}" style="background-color:
                            {% if application.status_id == 1 %}#E0FFFF{% elif application.status_id == 2 %}#90EE90{% else %}#F08080{% endif %}">
                            <p>{{ application.year }}</p>
                          </a>
                        </li>
                      {% endfor %}
                    </ul>
                  </div>
                {% endif %}
              </div>
            {% else %}
              <h5>{{ artist.name }}</h5>
            {% endif %}
          </div>
        {% endfor %}
      </div>
    </div>
-->
    <!-- Profile Badges -->
    <div class="row mt-5">
      <div class="col rounded" style="background-color: rgba(255, 255, 255, 0.5);">
        <h2 class="bello">Badges</h2>
        <p>Du har endnu ikke optjent nogen badges</p>
      </div>
    </div>
    <!-- Volunteer Modal -->
    {% for application in volunteer_applications %}
      {% if application %}
        <div class="modal fade" style="max-height:100vh;" id="modal{{ application.pk }}" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" style="min-width:50vw;max-height:50%;">
            <div class="modal-content" style="background-size:cover; background-image:url('{% if application.area__bg %}{{ MEDIA_URL|add:application.area.bg.url }}{% else %}{{ STATIC_DEV|add:'img/bg/home.jpg' }}{% endif %}');">
                <div class="modal-header">
                  <h1 class="modal-title bello" id="exampleModalLabel">{{ application.area }}</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body overflow-auto h-75">
                  <dl class="row">
                    <dt class="col-sm-3">Mail</dt>
                    <dd class="col-sm-9">{{ application.area.mail }}</dd>
                    <dt class="col-sm-3">Status</dt>
                    <dd class="col-sm-9">{{ application.status }}</dd>
                    <dt class="col-sm-3">Starttid</dt>
                    <dd class="col-sm-9">{{ application.area.start_time }}</dd>
                    <dt class="col-sm-3">Kommentar</dt>
                    <dd class="col-sm-9">{{ application.user_comment }}</dd>
                  </dl>
                </div>
                <div class="modal-footer opacity-25">
                  <div class="col-md-3 mx-auto">
                    {% if perms.year.change_volunteerapplication %}
                      <a class="btn btn-primary" href="{% url 'hzd:volunteer' pk=application.id %}?next={{ request.path }}">Redigér</a> 
                    {% endif %}
                    <a type="button" class="btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">Luk</a>
                    {% if perms.year.delete_volunteerapplication %}
                      <a class="btn btn-danger" href="#" data-bs-toggle="modal" data-bs-target="#deleteVolunteerModal">
                        Slet
                      </a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Delete Modal -->
        <div class="modal fade" id="deleteVolunteerModal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
          <div class="modal-dialog" style="min-width:50vw;">
            <div class="modal-content" style="background-size:cover; background-image:url('{{ STATIC_DEV|add:"img/bg/home.jpg" }}');">
              <div class="modal-header">
                <h1 class="modal-title bello" id="exampleModalLabel">Slet</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <p>Er du sikker?</p>
              </div>
              <div class="modal-footer">
                <form method="post" action="{% url 'hzd:volunteer_delete' application.id %}">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger">Slet det</button>
                </form>
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" aria-label="Close">
                  <p>Fortryd</p>
                </button>
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    {% endfor %}
  {% endif %}
{% endblock page_content %}

src/accounts/templates/accounts/profile_edit.html
{% extends "year/page.html" %}
{% block page_content %}

<div styl="background-image: url('{{ bg.image_url }}');">
    <!-- Include the reusable form template -->
    {% include 'form_snippet.html' with form=form method='post' action='' button_label='Opdater' %}
    <a href="{% url 'accounts:reset_password' %}" class="btn btn-secondary mt-3">Skift kodeord</a>
</div>

<!-- Delete Modal -->
{% if button_label_delete %}
  <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" style="min-width:50vw;">
      <div class="modal-content" style="background-size:cover; background-image:url('{{ STATIC_DEV|add:"img/bg/home.jpg" }}');">
        <div class="modal-header">
          <h1 class="modal-title bello" id="exampleModalLabel">Slet</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Er du sikker?</p>
        </div>
        <div class="modal-footer">
          <form method="post" action="{% url 'accounts:profile_delete' %}" onsubmit="console.log('Form submitted');">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Slet det</button>
          </form>
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal" aria-label="Close">
            <p>Fortryd</p>
          </button>
        </div>
      </div>
    </div>
  </div>
{% endif %}

{% endblock page_content %}